dht:
  app:
    node-ids:
      - mnopqrstuvwxyz123456
      - mnopqrstuvwxyz123477
      - mnopqrstuvwxyz123488
    ports:
      - 12888
      - 12889
      - 12890
    init-addresses:
      - router.utorrent.com:6881
      - router.bittorrent.com:6881